# Generated by Django 4.2.23 on 2025-08-13 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios_login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programmer',
            name='age',
        ),
        migrations.RemoveField(
            model_name='programmer',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='programmer',
            name='nickname',
        ),
    ]
