# Generated by Django 5.2.5 on 2025-09-15 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrotag',
            old_name='tag_id',
            new_name='tag',
        ),
    ]
